main: com.ihells.fishingloot.FishingLoot
name: FishingLoot
version: 1.0
author: "iHells#7514"
commands:
  rod:
    description: "Upgrade your current fishing rod!"
softdepend:
  - Vault
  - TokenManager